coverage:
  precision: 2
  round: up
  range: "70...100"

ignore:
  - ^src/main/java/edu/fiuba/algo3/vista.*
  - ^src/main/java/edu/fiuba/algo3/controladores.*
  - ^src/main/java/edu/fiuba/algo3/App.java
  - ^src/main/java/edu/fiuba/algo3/Main.java
  - ^src/main/java/edu/fiuba/algo3/SystemInfo.java
  - ^src/main/java/module-info.java
