@startuml

skinparam classAttributeIconSize 0
skinparam style strictuml

abstract class Continente <<abstract>> {
  - paises: ArrayList<Pais>
  + dominadoPor(unJugador: Jugador): Boolean
  + dominaCantidadDePaises(jugador: Jugador, cantidad: Integer): Boolean
  {abstract} + obtenerCantidadEjercito(): Integer
}

class Europa extends Continente {
  + obtenerCantidadEjercito(): Integer
}

class Asia extends Continente {
  + obtenerCantidadEjercito(): Integer
}

class Africa extends Continente {
  + obtenerCantidadEjercito(): Integer
}

class Oceania extends Continente {
  + obtenerCantidadEjercito(): Integer
}

class AmericaDelSur extends Continente {
  + obtenerCantidadEjercito(): Integer
}

class AmericaDelNorte extends Continente {
  + obtenerCantidadEjercito(): Integer
}

@enduml
