@startuml

class Pais{
    -List<Ejercito> ejercitos
    -List<Pais> limitrofes
    __
    +modificarEjercito(int cantidad)
    +atacarCon(int cantEjercitos)
    +defenderse()
}

class Batalla{
    +batallaEntre(Pais atacante, Pais defensor, int cantidadEjercitos)
    +comparar(Dado dadoAtacante, Dado dadoDefensor)
    +bool estaDesocupado()

}

Batalla --> "2 " Pais







@enduml