@startuml
title Ataque entre paises, Pais defensor como ganador
autoactivate on

actor Usuario
participant Juego
participant Batalla
participant "paisAtacante: Pais"
participant "paisDefensor: Pais"
participant Ejercito

Usuario -> Juego: atacarDesdeA(Pais atacante,Pais defensor, int cantidadEjercitos)
Juego -> Batalla: batallaEntre(Pais atacante, Pais defensor, int cantidadEjercitos)
Batalla -> "paisAtacante: Pais": atacarCon(int cantidadEjercitos)
loop "Para cada ejercito en cantidadEjercitos" 
"paisAtacante: Pais" -> Ejercito: tirarDado()
return Dado dado
end

return List<Dado> dadosAtacante
Batalla -> "paisDefensor: Pais": defender()

loop "Para 3 ejercitos"
"paisDefensor: Pais" -> Ejercito: tirarDado()
return Dado dado
end

return List<Dado> dadosDefensor

loop "Compara dado a dado"
Batalla -> Batalla: comparar(Dado dadoAtacante, Dado dadoDefensor)
Batalla -> "paisAtacante: Pais": modificarEjercito(-1)
end

Juego -> "paisDefensor: Pais": estaDesocupado()
return false

deactivate "paisAtacante: Pais"
deactivate Batalla
deactivate Juego

@enduml